### ISSUE TITLE
boxy2 - nettverkspunktet er utsatt

### ISSUE THREAD

**Issue by tingox** [bitraf/infrastructure#106]
boxy2 er ganske kritisk, ettersom den er døråpner for døra nede, og dørene inn til labben i Bitraf. Nettverkspunktet den er koblet til (nr. 79) er bak sofaen i labben. Dermed er det utsatt, og det hender at boxy2 ramler av nett hvis noen flytter på sofaen. Og da slutter døråpneren og fungere, uten at man får feilmelding.

Forslag til løsning: flytte boxy2 til et annet nettverkspunkt som ikke er så utsatt.

**Comment by eliasbakken** [comment]
Ligger det ikke en ethernet-boks i taket som kan nås?

**Comment by odinho** [comment]
Kva med å ha wifi som fallback og backup? Med automatisk varsling når ethernet-tilkoplinga er nede?

Har me noko monitoreringssystem? Typ icinga2? Det kunne ha sendt ein melding til #bitraf på IRC viss det hender.

**Comment by tingox** [comment]
jo, det er et nettverkspunkt i taket. Jeg tipper det er brukt til den ene eller begge switchene som er montert på søylene i labben. Kanskje det ligger en liten switch over himlingen med en ledig port?

**Comment by tingox** [comment]
FWIW, mastensg replaced theRJ-45 connector on the ethernet cable (the end that goes into network port number 79) yesterday, as it was broken (the catch that keeps the connector in place was broken off). Perhaps this will provide some more stability in the last few months.

**Comment by tingox** [comment]
Overcome by events - Bitraf has moved, this is not relevant any longer.
