### ISSUE TITLE
Harden wordpress

### ISSUE THREAD

**Issue by trygvis** [bitraf/infrastructure#116]
Implement these two security-related things:

- [ ] ~~https://www.hostinger.com/tutorials/xmlrpc-wordpress~~
- [ ] https://wordpress.org/support/topic/how-to-rename-wp-admin-properly/

**Comment by Kogni** [comment]
xmlrpc har vist seg å være nødvendig for å publishe Meetups automatisk i WP

**Comment by trygvis** [comment]
Ok, da dropper vi det punktet.

**Comment by trygvis** [comment]
The wordpress has been removed.
