### ISSUE TITLE
Create a setup for doorlock in Brenneriveien

### ISSUE THREAD

**Issue by eliasbakken** [bitraf/infrastructure#146]
We need door open systems for the new place we are moving to in September 2021. 
We suggest using Raspberry pi 3 with the D-lock "hat"

**Comment by tingox** [comment]
todo:
- check if we have necessary PCB's and components
- order anything missing
- find a suitable case (transparent, if possible), and order the required number
- create new boards, if required
- assemble the required number of doorlock boxes
- test (at least) one of the new boxes at current Bitraf location

**Comment by eliasbakken** [comment]
We have 2 Raspberry pi 3's available for testing.
One of the pis have been set up to unlock the only office on the second floor. 
The hostname is boxy2-eof, it listens to messages on firstdoor
We have aquired two cases from Jensa that can be used during testing.

**Comment by tingox** [comment]
hardware status:
- we have 11 dlock-cards that can be used
- jensa have ordered Pi3's, Swissbit microSD card and power supplies for 5 locks
boxes (enclosure) for the new locks are still a missing item. The two cases jensa provided was "tilovers" and ha didn't know where he got them.

**Comment by tingox** [comment]
status update
- Pi3's, Swissbit microSD card and power supplies for 5 locks have arrived
- boxes have been ordered

**Comment by tingox** [comment]
overcome by events - the doorlock in BV9 has been in service for quite a while now.
