### ISSUE TITLE
make ipv6 work

### ISSUE THREAD

**Issue by mastensg** [bitraf/infrastructure#2]
@trygvis and i tried to make ipv6 available to all the machines on bitraf's network, with autoconfiguration by dhcp6, but we have failed

**Comment by odinho** [comment]
The ever-lasting issue. Had some new people negatively find this yesterday. Could we disable ipv6 in the mean time, so we don't get this problem? Everyone new has to rediscover the issue which is a bit of a bummer.

**Comment by mastensg** [comment]
@odinho

**Comment by tingox** [comment]
Some debugging information.
The router has IPv6 configuration
`bix>show ipv6 int GigabitEthernet0/0
GigabitEthernet0/0 is up, line protocol is up
  IPv6 is enabled, link-local address is FE80::FA72:EAFF:FE10:3AE0 
  No Virtual link-local address(es):
  Global unicast address(es):
    2001:840:4B0B::1, subnet is 2001:840:4B0B::/48 
  Joined group address(es):
    FF02::1
    FF02::2
    FF02::1:2
    FF02::1:FF00:1
    FF02::1:FF10:3AE0
    FF05::1:3
  MTU is 1500 bytes
  ICMP error messages limited to one every 100 milliseconds
  ICMP redirects are enabled
  ICMP unreachables are sent
  ND DAD is enabled, number of DAD attempts: 1
  ND reachable time is 30000 milliseconds (using 30000)
  ND advertised reachable time is 0 (unspecified)
  ND advertised retransmit interval is 0 (unspecified)
  ND router advertisements are sent every 200 seconds
  ND router advertisements live for 1800 seconds
  ND advertised default router preference is Medium
  Hosts use DHCP to obtain routable addresses.
`
and that looks ok to me (but I'm no IPv6 expert)

**Comment by tingox** [comment]
On the dhcp side (still IPv6) the router has this:
```
bix>show ipv6 dhcp pool
bix>show ipv6 dhcp bind
bix>show ipv6 dhcp datab
bix>show ipv6 dhcp int
GigabitEthernet0/0 is in server mode
  Using pool: bitraf6
  Preference value: 0
  Hint from client: ignored
  Rapid-Commit: disabled
bix>show ipv6 dhcp | ?
  begin    Begin with the line that matches
  count    Count number of lines which match regexp
  exclude  Exclude lines that match
  format   Format the output using the specified spec file
  include  Include lines that match
  section  Filter a section of output
```
I'm not sure if there should be something more here.

**Comment by tingox** [comment]
The IPv6 neighbors table on the router shows
```
bix>show ipv6 neighbors 
IPv6 Address                              Age Link-layer Addr State Interface
FE80::B614:89FF:FE22:2840                   1 b414.8922.2840  STALE Gi0/1
FE80::C6A:2A04:1796:C73                   112 784f.4366.721d  STALE Gi0/0
FE80::1828:E0EC:D398:91D1                  50 e4ce.8f61.50ab  STALE Gi0/0
FE80::101A:C4AD:EF9A:F1A3                 123 dc2b.6132.5f5c  STALE Gi0/0
FE80::BA27:EBFF:FE51:131D                   6 b827.eb51.131d  STALE Gi0/0
FE80::1CC7:25B4:F094:5E7C                 232 1865.9072.a58c  STALE Gi0/0
FE80::564A:16FF:FEF4:CCEA                 127 544a.16f4.ccea  STALE Gi0/0
FE80::6CE7:141:80A3:4EA8                    2 7845.61bd.e43d  STALE Gi0/0
FE80::13:D509:2182:D62E                   229 7831.c1bc.001e  STALE Gi0/0
FE80::2486:E828:AD22:E23A                  63 f0d5.bf52.8e0b  STALE Gi0/0
FE80::2955:31CF:E62D:790F                  38 3ca9.f49f.1ee8  STALE Gi0/0
FE80::9AE7:F5FF:FEA3:1200                   4 98e7.f5a3.1200  STALE Gi0/0
FE80::86CF:BFFF:FE8A:9405                  71 84cf.bf8a.9405  STALE Gi0/0
2001:840:F000:4B0B::1                       1 b414.8922.2840  STALE Gi0/1
FE80::B2E5:EDFF:FE8E:A95B                   6 b0e5.ed8e.a95b  STALE Gi0/0
FE80::C88:C65D:BFE8:DBF2                  190 f024.7573.ff57  STALE Gi0/0
FE80::468A:5BFF:FE9F:A038                   1 448a.5b9f.a038  STALE Gi0/0
FE80::C1F9:EC80:B72D:2680                  56 f2de.f112.8069  STALE Gi0/0
FE80::AE37:43FF:FE4F:F58                    5 ac37.434f.0f58  STALE Gi0/0
FE80::E5:3146:C18E:2BCC                    48 38ca.da42.a1d3  STALE Gi0/0
FE80::D60B:1AFF:FEBB:31AD                  20 d40b.1abb.31ad  STALE Gi0/0
FE80::8806:7B45:A95A:23FD                   9 1c4b.d655.ade3  STALE Gi0/0
FE80::7A31:C1FF:FEC4:5AE0                  51 7831.c1c4.5ae0  STALE Gi0/0
FE80::8EF5:A3FF:FE39:BDDF                   5 8cf5.a339.bddf  STALE Gi0/0
FE80::F6F4:6FB9:EF0D:7742                 155 d8cb.8a9f.991a  STALE Gi0/0
FE80::6E:7AB9:ED3B:1FE7                     8 d896.95c5.36b0  STALE Gi0/0
FE80::1CF8:8B81:D745:E42B                 159 1c9e.461e.1cac  STALE Gi0/0
FE80::D879:7A0:5F75:DF8A                  155 d8cb.8a9f.991a  STALE Gi0/0
FE80::1CDE:170B:DE6:631C                    1 70ec.e443.f279  STALE Gi0/0
FE80::1819:1E84:B9E8:B64D                 210 a45e.60c4.31a1  STALE Gi0/0
FE80::1845:56C9:F302:BBB7                  52 c0f2.fbad.31ca  STALE Gi0/0
FE80::14D6:3E35:BBD8:4706                 120 784f.4373.249a  STALE Gi0/0
FE80::21:1551:858C:71B8                    64 5840.4ed3.7c80  STALE Gi0/0
FE80::4DF5:3324:555E:DCCB                 203 4ccc.6ab2.1fde  STALE Gi0/0
FE80::4E66:41FF:FE6D:5AA1                  14 4c66.416d.5aa1  STALE Gi0/0
FE80::BC8A:69E:8FA2:21D6                   48 e4a7.a08d.f5e0  STALE Gi0/0
FE80::105E:595C:A219:E678                 216 b8e8.563e.8ef2  STALE Gi0/0
FE80::F225:B7FF:FEEA:C65A                 180 f025.b7ea.c65a  STALE Gi0/0
FE80::654A:7C4C:22BA:D5D3                  65 ace0.105f.fd69  STALE Gi0/0
FE80::15DB:8978:C3C8:B81A                  12 001b.213f.5181  STALE Gi0/0
FE80::1845:1F6C:BF71:192D                  50 f4f1.5a2a.7d8b  STALE Gi0/0
FE80::9A01:A7FF:FEA6:3A25                 231 9801.a7a6.3a25  STALE Gi0/0
```
should it have more than one entry that is not link-local?

**Comment by tingox** [comment]
The router "runs" these IPv6 routing protocols
```
bix>show ipv6 proto 
IPv6 Routing Protocol is "connected"
IPv6 Routing Protocol is "ND"
IPv6 Routing Protocol is "static"
```
again, I'm not qualified to say if something is missing here.

**Comment by tingox** [comment]
The IPv6 routing table on the router
```
bix>show ipv6 route 
IPv6 Routing Table - default - 6 entries
Codes: C - Connected, L - Local, S - Static, U - Per-user Static route
       B - BGP, HA - Home Agent, MR - Mobile Router, R - RIP
       I1 - ISIS L1, I2 - ISIS L2, IA - ISIS interarea, IS - ISIS summary
       D - EIGRP, EX - EIGRP external, NM - NEMO, ND - Neighbor Discovery
       l - LISP
       O - OSPF Intra, OI - OSPF Inter, OE1 - OSPF ext 1, OE2 - OSPF ext 2
       ON1 - OSPF NSSA ext 1, ON2 - OSPF NSSA ext 2
S   ::/0 [1/0]
     via 2001:840:F000:4B0B::1
C   2001:840:4B0B::/48 [0/0]
     via GigabitEthernet0/0, directly connected
L   2001:840:4B0B::1/128 [0/0]
     via GigabitEthernet0/0, receive
C   2001:840:F000:4B0B::/64 [0/0]
     via GigabitEthernet0/1, directly connected
L   2001:840:F000:4B0B::2/128 [0/0]
     via GigabitEthernet0/1, receive
L   FF00::/8 [0/0]
     via Null0, receive
```
not sure what the significance of "receive" on some entries are.

**Comment by tingox** [comment]
The router has no IPv6 routers, which might be okay (or not)?
```
bix>show ipv6 routers default 
No default router
bix>show ipv6 routers         
```

**Comment by rkarlsba** [comment]
hm - kan det være at bix også sender RA ut på wan-sida? Det er et salig kaos der…

**Comment by rkarlsba** [comment]
Statisk adresse og statisk gateway 2001:840:f000:4b0b::1 funker

**Comment by lkarsten** [comment]
Er det sånn at uplink mot Powertech er på Gi0/1, tildelt IPv6-adresserom er 2001:840:4B0B::/48 og linknettet er på 2001:840:F000:4B0B::/64 ?

Første steg er å være sikker på at routeren selv har konnektivitet ut. Virker det å kjøre `ping ipv6 2001:700:300::208 source 2001:840:4b0b::1`? (en av NTNU sine navnetjenere) Evt, virker det uten den ekstra source-delen?

Jeg antar at "ipv6 unicast-routing" er satt/slått på? 

Re kommentaren om "ipv6 routers"; dette er for å sette opp routingprotokoller som OSPF og RIP og trengs ikke her. Statiske routes er nok.

Om man ikke har spesielle behov på klientsiden holder det å bruke RA / SLAAC i stedet for DHCPv6. Med "ipv6 address 2001:840:4b0b::1/64; ipv6 enable" på porten(e) mot klientene, antatt gi0/0, bør den siden være på plass. Det er en fordel å legge på "no ipv6 enable" der inntil man er sikker på at routeren har fungerende IPv6 ut.

**Comment by rkarlsba** [comment]
Det funker med IPv6 mot bite og VM-ene som kjører der. 2001:840:f000:4b0b::102/64 og f.eks. zabbix.karlsbakk.net på 2001:840:f000:4b0b::126. Gjetter at vi derfor har 2001:840:f000::/48 som nett, og at det bare er allokert 2001:840:f000:4b0b::/64 så langt. Det kan jo være greit å bruke ett av netta til klienter og ett til IoT og… Vi har 65536 nett å ta av, så det holder vel ei stund. Hva linknettet er, er jeg usikker på, men tviler på om det er så viktig. Angående RA/SLAAC, ja, det er nok det beste, men fortrinnsvis på et annet nett enn 4b0b, siden vi har servere, dører og sånt der nå. Å separere disse fra klienter og annet, er nok en vesentlig fordel den dagen vi strammer til sikkerheten. 

Vennlig hilsen 

roy 
-- 
Roy Sigurd Karlsbakk 
(+47) 98013356 
http://blogg.karlsbakk.net/ 
GPG Public key: http://karlsbakk.net/roysigurdkarlsbakk.pubkey.txt 
-- 
Da mihi sis bubulae frustrum assae, solana tuberosa in modo Gallico fricta, ac quassum lactatum coagulatum crassum. Quod me nutrit me destruit.

**Comment by lkarsten** [comment]
Søkte litt på nett og kom over https://bitraf.no:4433/wiki/index.php?title=Nettverk sin IPv6-seksjon som ser ut til å understøtte 2001:840:f000::/48 som generelt linknett-scop for Powertech.

Om man googler adresserommet det finner man en del andre (f.eks. pogostick.net) som har lignende mønster. (2001:840:f000:<kundenr>::2 på kunde-siden)

@rkarlsba det virker kanskje nå å legge maskinene sine på linknettet, men jeg tror ikke det er slik Powertech har ment at det skal gjøres. Det er ikke uvanlig å filtrere trafikk mot linknett fra verden, så du risikerer at det slutter å virke en dag powertech/broadnet finner det for godt.

**Comment by rkarlsba** [comment]
Hei 

Det var visst jeg som blingsa. Så litt likt ut der, men jeg tror jeg forstår hva Powertech har tenkt her. 

Link: 2001:840:F000:<kundeid>::/64 
LAN: 2001:840:<kundeid>::/48 

Så ja, 2001:840:f000::/64 er nok link, og vi burde få servere og klienter og sånt over på 2001:840:4b0b::/48. Jeg freslår at vi da setter opp minst to nett, f.eks. 2001:840:4b0b:1000::/64 og 2001:840:4b0b:2000::/64 for henholdsvis servere og klienter, så kan vi utvide seinere. Vad tycks? 

Vennlig hilsen 

roy 
-- 
Roy Sigurd Karlsbakk 
(+47) 98013356 
http://blogg.karlsbakk.net/ 
GPG Public key: http://karlsbakk.net/roysigurdkarlsbakk.pubkey.txt 
-- 
Da mihi sis bubulae frustrum assae, solana tuberosa in modo Gallico fricta, ac quassum lactatum coagulatum crassum. Quod me nutrit me destruit.

**Comment by trygvis** [comment]
IPv6 funker nå etter nattens restart. Lokalnettet er satt opp med SLAAC og alle maskinene på LAN får IPer i `2001:840:4B0B:1337/64`. Bix er `2001:840:4B0B:1337::1`

**Comment by rkarlsba** [comment]
bite.bitraf.no står visst på 2001:840:f000:4b0b::102/64 fremdeles. Har du satt av et nett til servere også? 

Vennlig hilsen 

roy 
-- 
Roy Sigurd Karlsbakk 
(+47) 98013356 
http://blogg.karlsbakk.net/ 
GPG Public key: http://karlsbakk.net/roysigurdkarlsbakk.pubkey.txt 
-- 
Da mihi sis bubulae frustrum assae, solana tuberosa in modo Gallico fricta, ac quassum lactatum coagulatum crassum. Quod me nutrit me destruit.

**Comment by trygvis** [comment]
Denne har blitt oppdatert med område for servere: https://bitraf.no/wiki/Nettverk#Offentlige_IPv6-adresser. Dine maskiner bruker feil nett, de bruker link-nettet mellom bitraf og Powertech. Jeg la inn noen nye adresser du kan bruke, endre de om du vil ha et annet mønster men hold deg innenfor 1000-nettet.

**Comment by rkarlsba** [comment]
Har du satt opp ruteren til å binde til 2001:840:4B0B:1000::1 også? får ikke pinga denne… 

Vennlig hilsen 

roy 
-- 
Roy Sigurd Karlsbakk 
(+47) 98013356 
http://blogg.karlsbakk.net/ 
GPG Public key: http://karlsbakk.net/roysigurdkarlsbakk.pubkey.txt 
-- 
Da mihi sis bubulae frustrum assae, solana tuberosa in modo Gallico fricta, ac quassum lactatum coagulatum crassum. Quod me nutrit me destruit.
