### ISSUE TITLE
bomba -> bite: p2k12

### ISSUE THREAD

**Issue by mastensg** [bitraf/infrastructure#7]
have the membership database run in its own virtual machine

what does it need?

- [ ] postgresql database: p2k12
- [ ] web server for p2k12.bitraf.no, (door.bitraf.no)
- [ ] whatever makes the doors unlock

**Comment by mastensg** [comment]
door services:
- `bitraf-guestlogin.service`
- `bitraf-iot-doorstatus.service`
- `bitraf-iot-opendoor3floor.service`

**Comment by trygvis** [comment]
New plan:

Create VM for p2k12, move postgresql database to the VM. Let p2k12 live as our internal trading system.

These are required:
- [ ] Create vm: p2k12
- [ ] Use ansible roles to create postgresql instance

These can be moved to separate issues later if not done right away:
- [ ] Move p2k12 related files to this VM
- [ ] Enable public access to https://p2k12.bitraf.no again.

**Comment by trygvis** [comment]
Fixed by p2k16.
