### ISSUE TITLE
Opplasting av filer til wiki fungerer ikke

### ISSUE THREAD

**Issue by Kogni** [bitraf/infrastructure#84]
Forsøk på opplasting gir følgende feilmelding: 
"Feil under oppretting av miniatyrbilde: /bin/bash: /usr/bin/convert: No such file or directory Error code: 127"

**Comment by mastensg** [comment]
@Kogni jeg har påført endringene i #85, og klarte å laste opp et bilde nå nettopp. kan du sjekke igjen?
