### ISSUE TITLE
mediawiki: upload of files >= 1 Megabyte fails

### ISSUE THREAD

**Issue by tingox** [bitraf/infrastructure#87]
When I try to upload a file (any file) with size >= 1 megabyte, it fails with
`413 Request Entity Too Large`
`nginx`

php.ini size variables for file uploads are correct:
`tingo@mediawiki:~$ grep _max_ /etc/php/7.0/fpm/php.ini`
`log_errors_max_len = 1024`
`post_max_size = 20M`
`upload_max_filesize = 20M`
so perhaps we need to change the nginx configuration too, ref: [Nginx error 413: Request entity too large Quick Fix](https://cnedelcu.blogspot.com/2013/09/nginx-error-413-request-entity-too-large.html)
(yes, that is the first relevant hit from a google search)

**Comment by tingox** [comment]
hmm, is there a proxy / reverse proxy in front of the nginx server for mediawiki? (I don't think there is, but have to ask anyway)

I have tried adding
`client_max_body_size 21M; `
to /etc/nginx/nginx.conf (http context)
and to /etc/nginx/sites-enabled/mediawiki (context server, location) for most locations
and then restarted nginx and php7.0-fpm, but I still get '413 Request Entity Too Large'.
Suggestions?

**Comment by trygvis** [comment]
Ah, yes, Bite is running in front as a proxy.

**Comment by tingox** [comment]
hmm, on marvin?

**Comment by trygvis** [comment]
No, sorry again. The wiki is running as an LXC guest on `bitnote`, The Nginx on `bitnode` also needs to be adjusted. Set it to something very big, 100MB or something like that and let the applications handle the actual size requirements.

**Comment by tingox** [comment]
Ok, I manually added `client_max_body_size 100M;` to /etc/nginx/sites-available/bitraf on bitnode and it works now. I can't seem to find that nginx config file (or template) in our ansible setup. Have I overlooked it, or isn't it part of ansible yet?

**Comment by tingox** [comment]
As for the mediawiki part  `client_max_body_size 21M;` in the server context is enough (I set it to 21M since we have 20M size in php settings. Not sure how big those requests are without the file upload data.)

**Comment by trygvis** [comment]
@tingox you're right, bitnode's config is not in Ansible yet.

**Comment by trygvis** [comment]
This looks resolved now.

**Comment by tingox** [comment]
Yes.
