### ISSUE TITLE
sette opp en enklere issue tracker

### ISSUE THREAD

**Issue by tingox** [bitraf/infrastructure#98]
Bitraf kan ha nytte av en bedre "issue tracker". Fordeler det kan gi oss:
- større deltagelse fra vanlige brukere (forutsetter at den er enkel i bruk)
- bedre rapportering (kan brukes til oppsummering på hel- og halvårsmøter for eksempel)
- bedre synlighet for aktiviteter og ting som blir fikset "under panseret"

**Comment by mastensg** [comment]
lignende ting som allerede fins:

- #forslagskassa på slack
- Ønsket utstyr: https://bitraf.no/wiki/%C3%98nsket_Utstyr_p%C3%A5_Bitraf
- Ønskede fixer: https://bitraf.no/wiki/Ting_Vi_%C3%98nsker_Fikset
- systemet som denne meldingen er inni: https://github.com/bitraf/infrastructure/issues

**Comment by trygvis** [comment]
Vi beholder de stedene vi har i dag.
